In [13]:
import geopandas as gpd
from tqdm.auto import tqdm
import pandas as pd
seawalls = gpd.read_file("aklc_seawalls.geojson")
seawalls

,ParkGardenTurfRoute.OBJECTID,ParkGardenTurfRoute.AssetGroup,ParkGardenTurfRoute.SAPID,ParkGardenTurfRoute.Shape_Length,SAPPARK_DATA.DESCRIPTION,SAPPARK_DATA.SITE,SAPPARK_DATA.SITEDESCRIPTION,SAPPARK_DATA.LOCALBOARD,SAPPARK_DATA.SeismicAssessmentDate,SAPPARK_DATA.SeismicAssessmentScore,SAPPARK_DATA.SeismicAssessmentStatus,SAPPARK_DATA.SeismicAssessmentType,geometry
0,5554,Wall,1000057824,171.200562,SWAL-Along shoreline,21545,Beihlers Road Foreshore,Manurewa,None,0,,0,"MULTILINESTRING ((174.8655 -37.05119, 174.8653..."
1,5592,Wall,1000013119,61.361211,SWAL-N of Boatramp,11345,Sandys Parade,Waitakere Ranges,None,0,,0,"LINESTRING (174.64164 -36.96633, 174.64171 -36..."
2,5603,Wall,1000058435,4.217856,SWAL-Gabion Basket Rgi02,10063,Roberta Reserve,Orakei,None,0,,0,"LINESTRING (174.87982 -36.86473, 174.87986 -36..."
3,5634,Retaining Wall,1000108633,205.151123,SWAL-Stone-New seawall-S2,10702,Waiomanu Reserve (aka Magazine Bay),Franklin,None,0,,0,"LINESTRING (175.05464 -36.88287, 175.05458 -36..."
4,5658,Wall,1000080158,103.355986,SWAL-Gabion Basket Rwt67,20501,Endeavour Park,Waitemata,None,0,,0,"LINESTRING (174.78188 -36.86798, 174.78177 -36..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
721,86124,Retaining Wall,1000047918,22.479216,SWAL-Adj boatramp end of res,21552,Te Pene Reserve (Aka Tracey'S Walkway),Franklin,None,0,,0,"LINESTRING (175.04151 -36.87777, 175.04157 -36..."
722,86134,Retaining Wall,1000132107,8.908625,SWAL-Groyne-grouted stone,23410,Goble/Channel View Rd Reserve,Franklin,None,0,,0,"LINESTRING (174.70534 -37.14714, 174.70528 -37..."
723,87994,Retaining Wall,1000101054,326.766958,"SWAL-Surrounding reserve, Nth bridge-S1",10746,Jack Lachlan Drive Esplanade Reserve,Franklin,None,0,,0,"LINESTRING (174.98876 -36.89101, 174.9889 -36...."
724,87996,Retaining Wall,1000109724,335.113337,SWAL-Btwn carpark & Marina-S2,10746,Jack Lachlan Drive Esplanade Reserve,Franklin,None,0,,0,"LINESTRING (174.98629 -36.89074, 174.9863 -36...."
725,89369,Wall,1000080155,14.999955,SWAL-Gabion Basket Rwt64,20501,Endeavour Park,Waitemata,None,0,,0,"LINESTRING (174.78206 -36.86854, 174.78204 -36..."

In [2]:
transects = gpd.read_file("transects_extended.geojson")
transects

,id,site_id,orientation,along_dist,along_dist_norm,beach_slope,cil,ciu,trend,n_points,n_points_nonan,r2_score,mae,mse,rmse,intercept,ERODIBILITY,geometry
0,aus0001-0000,aus0001,104.347648,0.000000,0.000000,0.085,0.0545,0.2000,-1.441081,767.0,428.0,0.168420,28.102591,1263.560863,35.546601,179.085729,None,"LINESTRING (153.26555 -24.7007, 153.26938 -24...."
1,aus0001-0001,aus0001,93.495734,98.408334,0.002935,0.050,0.0387,0.0640,-1.037105,767.0,569.0,0.097874,25.419324,1033.770813,32.152306,212.247788,None,"LINESTRING (153.26525 -24.7019, 153.2692 -24.7..."
2,aus0001-0002,aus0001,82.069341,198.408334,0.005918,0.050,0.0428,0.0647,-0.680019,767.0,588.0,0.053927,22.632907,838.007507,28.948359,205.106151,None,"LINESTRING (153.26539 -24.70316, 153.26931 -24..."
3,aus0001-0003,aus0001,81.192757,298.402523,0.008900,0.055,0.0480,0.0659,-0.405198,767.0,598.0,0.023412,20.749758,698.653187,26.432048,191.745881,None,"LINESTRING (153.26555 -24.70408, 153.26945 -24..."
4,aus0001-0004,aus0001,81.065473,398.402523,0.011882,0.075,0.0614,0.0922,-0.090025,767.0,608.0,0.001277,19.889328,655.810616,25.608800,175.092121,None,"LINESTRING (153.2657 -24.70497, 153.26961 -24...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148189,nzd0604-0006,nzd0604,NaN,NaN,NaN,0.015,0.0137,0.0154,1.617348,354.0,340.0,0.099161,27.201442,1280.384719,35.782464,284.319742,None,"LINESTRING (175.17153 -36.94882, 175.1696 -36...."
148190,nzd0604-0007,nzd0604,NaN,NaN,NaN,0.010,0.0100,0.0114,-0.200530,354.0,348.0,0.004486,16.607071,481.482002,21.942698,336.186244,None,"LINESTRING (175.17234 -36.94851, 175.17041 -36..."
148191,nzd0604-0008,nzd0604,NaN,NaN,NaN,0.015,0.0146,0.0157,0.481883,354.0,346.0,0.029615,14.782436,412.410982,20.307904,289.699114,None,"LINESTRING (175.17356 -36.94778, 175.17058 -36..."
148192,nzd0604-0009,nzd0604,NaN,NaN,NaN,0.010,0.0100,0.0103,3.734130,354.0,333.0,0.334384,31.409671,1475.331264,38.410041,293.304520,None,"LINESTRING (175.1747 -36.9462, 175.1703 -36.94..."
148193,nzd0604-0010,nzd0604,NaN,NaN,NaN,0.015,0.0146,0.0174,-0.224829,354.0,352.0,0.006239,15.094799,447.180008,21.146631,294.268387,None,"LINESTRING (175.17484 -36.94532, 175.17038 -36..."

In [3]:
intersecting_transects = transects[transects.intersects(seawalls.union_all())]
intersecting_transects

,id,site_id,orientation,along_dist,along_dist_norm,beach_slope,cil,ciu,trend,n_points,n_points_nonan,r2_score,mae,mse,rmse,intercept,ERODIBILITY,geometry
100706,nzd0133-0001,nzd0133,103.627378,100.000000,0.166998,0.010,0.0100,0.0101,-4.901561,535.0,504.0,0.396798,34.930427,1879.217181,43.349939,539.774473,None,"LINESTRING (174.70564 -36.54328, 174.71568 -36..."
100707,nzd0133-0002,nzd0133,108.779187,199.897163,0.333824,0.015,0.0147,0.0152,-0.680907,535.0,532.0,0.042324,18.591036,552.389776,23.502974,409.481504,None,"LINESTRING (174.70552 -36.5437, 174.71531 -36...."
100708,nzd0133-0003,nzd0133,114.077173,299.897163,0.500822,0.025,0.0240,0.0286,-0.552038,535.0,534.0,0.075979,11.404218,199.072014,14.109288,387.322001,None,"LINESTRING (174.7053 -36.54408, 174.71474 -36...."
100709,nzd0133-0004,nzd0133,112.705386,399.893341,0.667813,0.045,0.0397,0.0496,-0.411159,535.0,533.0,0.067238,9.202252,126.186377,11.233271,376.538216,None,"LINESTRING (174.70489 -36.54481, 174.71443 -36..."
100710,nzd0133-0005,nzd0133,102.823909,499.117482,0.833515,0.055,0.0500,0.0639,-0.085853,535.0,533.0,0.003750,8.714894,105.375048,10.265235,374.163130,None,"LINESTRING (174.70436 -36.54601, 174.71443 -36..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102220,nzd0200-0101,nzd0200,249.127846,1199.612913,0.106545,0.025,0.0237,0.0270,0.464918,495.0,491.0,0.034585,15.310273,381.303872,19.527004,445.729377,None,"LINESTRING (174.65808 -37.28142, 174.64844 -37..."
148137,nzd0599-0000,nzd0599,NaN,NaN,NaN,0.065,0.0609,0.0714,0.265899,669.0,668.0,0.108637,4.525740,32.470969,5.698330,178.161747,None,"LINESTRING (174.8049 -36.82037, 174.80868 -36...."
148138,nzd0599-0001,nzd0599,NaN,NaN,NaN,0.090,0.0795,0.0997,0.355553,669.0,668.0,0.241422,3.760452,22.233977,4.715292,164.651236,None,"LINESTRING (174.80538 -36.82098, 174.80917 -36..."
148143,nzd0599-0006,nzd0599,NaN,NaN,NaN,0.115,0.1033,0.1267,0.106838,669.0,668.0,0.085108,2.038715,6.868112,2.620708,183.917052,None,"LINESTRING (174.80781 -36.82406, 174.81154 -36..."
148145,nzd0599-0008,nzd0599,NaN,NaN,NaN,0.100,0.0874,0.1107,-0.123979,669.0,669.0,0.072356,2.725583,11.084847,3.329391,188.457776,None,"LINESTRING (174.80882 -36.82526, 174.81253 -36..."

In [4]:
intersection_points = intersecting_transects.intersection(seawalls.union_all())
intersection_points

100706    POINT (174.70924 -36.54395)
100707    POINT (174.70908 -36.54464)
100708    POINT (174.70882 -36.54531)
100709    POINT (174.70841 -36.54596)
100710    POINT (174.70809 -36.54666)
                     ...
102220    POINT (174.65518 -37.28234)
148137    POINT (174.80618 -36.81972)
148138    POINT (174.80655 -36.82038)
148143    POINT (174.80912 -36.82335)
148145    POINT (174.81013 -36.82455)
Length: 83, dtype: geometry

In [5]:
intersection_points.geom_type.value_counts()

Point         82
MultiPoint     1
Name: count, dtype: int64

In [6]:
def reduce_to_furthest_point(idx, geom):
    if geom.geom_type == "MultiPoint":
        line = intersecting_transects.loc[idx, "geometry"]
        return max(geom.geoms, key=line.project)
    return geom

intersection_points = gpd.GeoSeries(
    [reduce_to_furthest_point(idx, geom) for idx, geom in intersection_points.items()],
    index=intersection_points.index,
    crs=intersection_points.crs,
    name=intersection_points.name,
)

intersection_points.geom_type.value_counts()

Point    83
Name: count, dtype: int64

In [7]:
intersecting_transects["origin_distance_to_seawall"] = intersecting_transects.to_crs(2193).project(intersection_points.to_crs(2193))
intersecting_transects["origin_distance_to_seawall"].describe()

/home/ubuntu/.local/lib/python3.12/site-packages/geopandas/geodataframe.py:1968: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

count     83.000000
mean     299.258100
std       59.119661
min       58.330175
25%      284.951840
50%      321.599391
75%      333.530107
max      350.870500
Name: origin_distance_to_seawall, dtype: float64

In [19]:
intersecting_transects.set_index("id").origin_distance_to_seawall

id
nzd0133-0001    330.461937
nzd0133-0002    334.948186
nzd0133-0003    343.246395
nzd0133-0004    339.870770
nzd0133-0005    341.045040
                   ...
nzd0200-0101    276.883685
nzd0599-0000    135.199524
nzd0599-0001    123.604208
nzd0599-0006    140.502828
nzd0599-0008    141.064355
Name: origin_distance_to_seawall, Length: 83, dtype: float64

In [29]:
results = []
for site_id in tqdm(intersecting_transects.site_id.unique()):
    df = pd.read_csv(f"data/{site_id}/transect_time_series_tidally_corrected.csv").set_index("dates")
    results.append((df - intersecting_transects.set_index("id").origin_distance_to_seawall).dropna(axis=1, how="all"))
results = pd.concat(results, axis=1).sort_index()
results.to_csv("seawall_distance.csv")
results

  0%|          | 0/14 [00:00<?, ?it/s]

,nzd0133-0001,nzd0133-0002,nzd0133-0003,nzd0133-0004,nzd0133-0005,nzd0137-0002,nzd0137-0003,nzd0137-0004,nzd0137-0005,nzd0138-0000,...,nzd0174-0003,nzd0174-0004,nzd0174-0010,nzd0174-0013,nzd0174-0015,nzd0200-0101,nzd0599-0000,nzd0599-0001,nzd0599-0006,nzd0599-0008
dates,,,,,,,,,,,,,,,,,,,,,
1999-07-18 21:58:25+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-07-18 21:58:49+00:00,NaN,NaN,NaN,NaN,NaN,NaN,26.23797,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.155645
1999-08-26 22:04:44+00:00,NaN,NaN,19.313605,26.13923,26.15496,66.875113,41.47797,34.457637,39.006813,115.763634,...,47.346631,51.331815,61.084373,61.649869,51.998021,NaN,NaN,NaN,NaN,NaN
1999-08-26 22:05:08+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,151.856315,26.260476,27.465792,34.777172,42.185645
1999-09-11 22:04:40+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-02-26 22:06:01+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,40.366631,46.031815,60.744373,65.339869,52.658021,NaN,45.260476,48.215792,52.037172,50.945645
2026-03-13 22:11:49+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34.216631,48.881815,60.444373,65.979869,48.148021,NaN,NaN,NaN,NaN,NaN
2026-03-13 22:12:13+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,234.886315,42.990476,37.775792,40.417172,37.555645
2026-03-22 22:05:33+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-22 22:05:57+00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,199.456315,53.760476,42.885792,45.657172,38.595645